#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_OUTPUT_PATH="${ROOT_DIR}/backend/requirements.txt"
OUTPUT_PATH="${DEFAULT_OUTPUT_PATH}"
CHECK_ONLY=0

usage() {
  printf 'Usage: %s [--check] [--output PATH]\n' "$(basename "$0")" >&2
}

require_commands() {
  local command_name
  for command_name in "$@"; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
    printf 'required command not found: %s\n' "${command_name}" >&2
      exit 1
    fi
  done
}

while (($# > 0)); do
  case "$1" in
    --check)
      CHECK_ONLY=1
      shift
      ;;
    --output)
      if (($# < 2)); then
        usage
        exit 1
      fi
      OUTPUT_PATH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown argument: %s\n' "$1" >&2
      usage
      exit 1
      ;;
  esac
done

require_commands uv python3 cmp mktemp

RAW_EXPORT_PATH="$(mktemp)"
NORMALIZED_EXPORT_PATH="$(mktemp)"

cleanup() {
  rm -f "${RAW_EXPORT_PATH}" "${NORMALIZED_EXPORT_PATH}"
}

trap cleanup EXIT

uv export \
  --project "${ROOT_DIR}/backend" \
  --format requirements.txt \
  --locked \
  --no-dev \
  --no-header \
  --no-annotate \
  --no-editable \
  --no-hashes \
  >"${RAW_EXPORT_PATH}"

RAW_EXPORT_PATH="${RAW_EXPORT_PATH}" NORMALIZED_EXPORT_PATH="${NORMALIZED_EXPORT_PATH}" python3 - <<'PY'
from __future__ import annotations

import os
from pathlib import Path

raw_path = Path(os.environ["RAW_EXPORT_PATH"])
normalized_path = Path(os.environ["NORMALIZED_EXPORT_PATH"])

raw_lines = raw_path.read_text(encoding="utf-8").splitlines()
normalized_lines: list[str] = []
rewrote_local_package = False

for line in raw_lines:
    if line in {".", "-e ."}:
        normalized_lines.append("./backend")
        rewrote_local_package = True
        continue
    normalized_lines.append(line)

if not rewrote_local_package:
    raise SystemExit("uv export did not include the backend local package reference")

normalized_path.write_text(
    "# Generated by ./scripts/export_backend_requirements.sh; do not edit by hand.\n"
    + "\n".join(normalized_lines)
    + "\n",
    encoding="utf-8",
)
PY

if ((CHECK_ONLY)); then
  if [[ ! -f "${OUTPUT_PATH}" ]]; then
    printf 'requirements file is stale or missing: %s\n' "${OUTPUT_PATH}" >&2
    exit 1
  fi

  if ! cmp -s "${NORMALIZED_EXPORT_PATH}" "${OUTPUT_PATH}"; then
    printf 'requirements file is stale: %s\n' "${OUTPUT_PATH}" >&2
    exit 1
  fi

  printf 'requirements file is up to date: %s\n' "${OUTPUT_PATH}" >&2
  exit 0
fi

mkdir -p "$(dirname "${OUTPUT_PATH}")"
cp "${NORMALIZED_EXPORT_PATH}" "${OUTPUT_PATH}"
printf 'wrote %s\n' "${OUTPUT_PATH}" >&2
