#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${ROOT_DIR}/backend"
DEFAULT_OUTPUT_PATH="${BACKEND_DIR}/requirements.txt"
LINUX_CUDA_OUTPUT_PATH="${BACKEND_DIR}/requirements-linux-cuda.txt"
WSL_ROCM_OUTPUT_PATH="${BACKEND_DIR}/requirements-wsl-rocm.txt"
OUTPUT_PATH="${DEFAULT_OUTPUT_PATH}"
CHECK_ONLY=0
ALL_ARTIFACTS=1
PYTHON_VERSION="3.11"
PYTHON_BIN="${BACKEND_PYTHON:-}"

if [[ -z "${PYTHON_BIN}" ]]; then
  if [[ -x "${BACKEND_DIR}/.venv/bin/python" ]]; then
    PYTHON_BIN="${BACKEND_DIR}/.venv/bin/python"
  else
    PYTHON_BIN="python3"
  fi
fi

usage() {
  printf 'Usage: %s [--check] [--output PATH]\n' "$(basename "$0")" >&2
}

require_commands() {
  local command_name
  for command_name in "$@"; do
    if ! command -v "${command_name}" >/dev/null 2>&1; then
      printf 'required command not found: %s\n' "${command_name}" >&2
      exit 1
    fi
  done
}

while (($# > 0)); do
  case "$1" in
    --check)
      CHECK_ONLY=1
      shift
      ;;
    --output)
      if (($# < 2)); then
        usage
        exit 1
      fi
      OUTPUT_PATH="$2"
      ALL_ARTIFACTS=0
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'unknown argument: %s\n' "$1" >&2
      usage
      exit 1
      ;;
  esac
done

require_commands uv "${PYTHON_BIN}" cmp mktemp

GENERIC_INPUT_PATH="$(mktemp)"
GENERIC_RAW_PATH="$(mktemp)"
GENERIC_NORMALIZED_PATH="$(mktemp)"
GENERIC_CONSTRAINTS_PATH="$(mktemp)"
LINUX_CUDA_INPUT_PATH="$(mktemp)"
LINUX_CUDA_RAW_PATH="$(mktemp)"
LINUX_CUDA_NORMALIZED_PATH="$(mktemp)"
WSL_ROCM_INPUT_PATH="$(mktemp)"
WSL_ROCM_RAW_PATH="$(mktemp)"
WSL_ROCM_NORMALIZED_PATH="$(mktemp)"

cleanup() {
  rm -f \
    "${GENERIC_INPUT_PATH}" "${GENERIC_RAW_PATH}" "${GENERIC_NORMALIZED_PATH}" "${GENERIC_CONSTRAINTS_PATH}" \
    "${LINUX_CUDA_INPUT_PATH}" "${LINUX_CUDA_RAW_PATH}" "${LINUX_CUDA_NORMALIZED_PATH}" \
    "${WSL_ROCM_INPUT_PATH}" "${WSL_ROCM_RAW_PATH}" "${WSL_ROCM_NORMALIZED_PATH}"
}

trap cleanup EXIT

write_generic_input() {
  printf './backend\n' >"${GENERIC_INPUT_PATH}"
}

write_profile_input() {
  local profile_name="$1"
  local destination_path="$2"

  PROFILE_NAME="${profile_name}" BACKEND_PYPROJECT_PATH="${BACKEND_DIR}/pyproject.toml" DESTINATION_PATH="${destination_path}" "${PYTHON_BIN}" - <<'PY'
from __future__ import annotations

import os
import tomllib
from pathlib import Path

profile_name = os.environ["PROFILE_NAME"]
pyproject_path = Path(os.environ["BACKEND_PYPROJECT_PATH"])
destination_path = Path(os.environ["DESTINATION_PATH"])
data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))

if profile_name == "linux-cuda":
    requirements = data["dependency-groups"]["linux-cuda"]
elif profile_name == "wsl-rocm":
    requirements = data["tool"]["nyaru"]["backend-accelerator-profiles"]["wsl-rocm"]["requirements"]
else:
    raise SystemExit(f"unsupported profile: {profile_name}")

destination_path.write_text("\n".join(requirements) + "\n", encoding="utf-8")
PY
}

read_wsl_rocm_extra_index_url() {
  BACKEND_PYPROJECT_PATH="${BACKEND_DIR}/pyproject.toml" "${PYTHON_BIN}" - <<'PY'
from __future__ import annotations

import os
import tomllib
from pathlib import Path

pyproject_path = Path(os.environ["BACKEND_PYPROJECT_PATH"])
data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
print(data["tool"]["nyaru"]["backend-accelerator-profiles"]["wsl-rocm"]["extra-index-url"])
PY
}

normalize_requirements_file() {
  local raw_path="$1"
  local normalized_path="$2"

  RAW_EXPORT_PATH="${raw_path}" NORMALIZED_EXPORT_PATH="${normalized_path}" "${PYTHON_BIN}" - <<'PY'
from __future__ import annotations

import os
from pathlib import Path

raw_path = Path(os.environ["RAW_EXPORT_PATH"])
normalized_path = Path(os.environ["NORMALIZED_EXPORT_PATH"])

raw_lines = raw_path.read_text(encoding="utf-8").splitlines()
normalized_lines: list[str] = []

for line in raw_lines:
    if line in {".", "-e ."}:
        normalized_lines.append("./backend")
        continue
    normalized_lines.append(line)

normalized_path.write_text(
    "# Generated by ./scripts/export_backend_requirements.sh; do not edit by hand.\n"
    + "\n".join(normalized_lines)
    + "\n",
    encoding="utf-8",
)
PY
}

write_constraints_file() {
  local source_path="$1"
  local destination_path="$2"

  SOURCE_REQUIREMENTS_PATH="${source_path}" DESTINATION_PATH="${destination_path}" "${PYTHON_BIN}" - <<'PY'
from __future__ import annotations

import os
from pathlib import Path

source_path = Path(os.environ["SOURCE_REQUIREMENTS_PATH"])
destination_path = Path(os.environ["DESTINATION_PATH"])

constraint_lines: list[str] = []
for line in source_path.read_text(encoding="utf-8").splitlines():
    normalized = line.strip()
    if not normalized or normalized.startswith("#") or normalized == "./backend":
        continue
    constraint_lines.append(normalized)

destination_path.write_text("\n".join(constraint_lines) + "\n", encoding="utf-8")
PY
}

compile_generic_requirements() {
  write_generic_input
  (
    cd "${ROOT_DIR}"
    uv pip compile "${GENERIC_INPUT_PATH}" \
      --project "${BACKEND_DIR}" \
      --python-version "${PYTHON_VERSION}" \
      --no-header \
      --no-annotate \
      >"${GENERIC_RAW_PATH}"
  )
  normalize_requirements_file "${GENERIC_RAW_PATH}" "${GENERIC_NORMALIZED_PATH}"
  write_constraints_file "${GENERIC_NORMALIZED_PATH}" "${GENERIC_CONSTRAINTS_PATH}"
}

compile_linux_cuda_requirements() {
  write_profile_input "linux-cuda" "${LINUX_CUDA_INPUT_PATH}"
  (
    cd "${ROOT_DIR}"
    uv pip compile "${LINUX_CUDA_INPUT_PATH}" \
      --project "${BACKEND_DIR}" \
      --python-version "${PYTHON_VERSION}" \
      --constraints "${GENERIC_CONSTRAINTS_PATH}" \
      --no-header \
      --no-annotate \
      >"${LINUX_CUDA_RAW_PATH}"
  )
  normalize_requirements_file "${LINUX_CUDA_RAW_PATH}" "${LINUX_CUDA_NORMALIZED_PATH}"
}

compile_wsl_rocm_requirements() {
  local extra_index_url
  extra_index_url="$(read_wsl_rocm_extra_index_url)"
  write_profile_input "wsl-rocm" "${WSL_ROCM_INPUT_PATH}"
  (
    cd "${ROOT_DIR}"
    uv pip compile "${WSL_ROCM_INPUT_PATH}" \
      --project "${BACKEND_DIR}" \
      --python-version "${PYTHON_VERSION}" \
      --constraints "${GENERIC_CONSTRAINTS_PATH}" \
      --extra-index-url "${extra_index_url}" \
      --index-strategy unsafe-best-match \
      --emit-index-url \
      --no-header \
      --no-annotate \
      >"${WSL_ROCM_RAW_PATH}"
  )
  normalize_requirements_file "${WSL_ROCM_RAW_PATH}" "${WSL_ROCM_NORMALIZED_PATH}"
}

write_generated_file() {
  local generated_path="$1"
  local target_path="$2"

  mkdir -p "$(dirname "${target_path}")"
  cp "${generated_path}" "${target_path}"
  printf 'wrote %s\n' "${target_path}" >&2
}

check_generated_file() {
  local generated_path="$1"
  local target_path="$2"

  if [[ ! -f "${target_path}" ]]; then
    printf 'requirements file is stale or missing: %s\n' "${target_path}" >&2
    return 1
  fi

  if ! cmp -s "${generated_path}" "${target_path}"; then
    printf 'requirements file is stale: %s\n' "${target_path}" >&2
    return 1
  fi

  printf 'requirements file is up to date: %s\n' "${target_path}" >&2
}

compile_generic_requirements

if ((ALL_ARTIFACTS)); then
  compile_linux_cuda_requirements
  compile_wsl_rocm_requirements
fi

if ((CHECK_ONLY)); then
  check_generated_file "${GENERIC_NORMALIZED_PATH}" "${OUTPUT_PATH}"

  if ((ALL_ARTIFACTS)); then
    check_generated_file "${LINUX_CUDA_NORMALIZED_PATH}" "${LINUX_CUDA_OUTPUT_PATH}"
    check_generated_file "${WSL_ROCM_NORMALIZED_PATH}" "${WSL_ROCM_OUTPUT_PATH}"
  fi

  exit 0
fi

write_generated_file "${GENERIC_NORMALIZED_PATH}" "${OUTPUT_PATH}"

if ((ALL_ARTIFACTS)); then
  write_generated_file "${LINUX_CUDA_NORMALIZED_PATH}" "${LINUX_CUDA_OUTPUT_PATH}"
  write_generated_file "${WSL_ROCM_NORMALIZED_PATH}" "${WSL_ROCM_OUTPUT_PATH}"
fi
